name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: echo-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Replace
        uses: ./actions/replace_path
      - name: Upload
        uses: ./actions/upload_to_s3